server:
 port: 8089 

spring:
 datasource:
  url: jdbc:mysql://192.168.31.162:3306/test?serverTimezone=GMT%2B8 
  username: root 
  password: 123 
  driver-class-name: com.mysql.cj.jdbc.Driver 

mybatis:
 mapper-locations: classpath*:mapper/*.xml 

jackson:
#\u8F6C\u6362\u5BF9\u8C61\u65F6\u8FC7\u6EE4\u6389null\u503C
 default-property-inclusion: non_null 
#\u51FA\u53C2\u65F6\u6240\u6709\u5C5E\u6027\u81EA\u52A8\u8F6C\u4E0B\u5212\u7EBF\u98CE\u683C
 property-naming-strategy: SNAKE_CASE 